# -*- coding: utf-8 -*-
"""PyPoll

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xSoYhxVIKZ-hXI-2V6Ao78dc1S_uLb1
"""

#import data
import pandas as pd
df = pd.read_csv('election_data.csv')

#Total nuber of votes
votes = 0
for i in range(len(df)):
  votes += 1

#List of candidates
candidates = []
for i in range(len(df)):
    if df['Candidate'][i] not in candidates:
        candidates.append(df['Candidate'][i])

Stockham = 0
DeGette = 0
Doane = 0

for i in range(len(df)):
  if df['Candidate'][i] == 'Charles Casper Stockham':
    Stockham += 1
  if df['Candidate'][i] == 'Diana DeGette':
    DeGette += 1
  else:
    Doane += 1

StockPercent = Stockham/votes * 100
DeGettePercent = DeGette/votes * 100
DoanePercent = Doane/votes * 100

# Find the winner
winner = max(Stockham, DeGette, Doane)

# Output the analysis to a text file
output_file = "PyPoll.txt"

with open(output_file, "w") as file:
    file.write("Election Results\n")
    file.write("-------------------------\n")
    file.write(f"Total Votes: {votes}\n")
    file.write("-------------------------\n")
    file.write(f"Charles Stockham: {StockPercent:.3f}% ({Stockham})\n")
    file.write(f"Diana DeGette: {DeGettePercent:.3f}% ({DeGette})\n")
    file.write(f"Raymon Anothony Doane: {DoanePercent:.3f}% ({Doane})\n")
    file.write("-------------------------\n")
    file.write(f"Winner: {'Charles Casper Stockham' if winner == Stockham else 'Diana DeGette' if winner == DeGette else 'Doane'}\n")
    file.write("-------------------------\n")

# Print the analysis to the console
with open(output_file, "r") as file:
    print(file.read())