# -*- coding: utf-8 -*-
"""PyBank

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GbKA1KXvl0KrZRQN2rtbJoTrH5iqIcFo
"""

#Import pandas and csv file
import pandas as pd
budget = pd.read_csv("budget_data.csv")

#Store header rows
headers = list(budget.columns)

#Count the number of entries to get the total number of months
months = 0
for i in range(len(budget)):
  months += 1

#Calculate net total profit/loss
net = 0
for i in range(len(budget)):
  net += budget["Profit/Losses"][i]

#Average of change in profits over entire period
budget['Change'] = budget['Profit/Losses'].diff()
average_change = budget['Change'].mean()

#Greatest increase in profits
greatest = 0
date1 = ''
for i in range(len(budget)):
  if greatest < budget['Change'][i]:
    greatest = budget['Change'][i]
    date1 = budget['Date'][i]
greatest = int(greatest)

#Greatest decrease in profits
smallest = 0
date2 = ''
for i in range(len(budget)):
  if smallest > budget['Change'][i]:
    smallest = budget['Change'][i]
    date2 = budget['Date'][i]
smallest = int(smallest)

# Output the analysis to a text file
output_file = "PyBank.txt"

with open(output_file, "w") as file:
    file.write("Financial Analysis\n")
    file.write("-------------------------\n")
    file.write(f"Total months: {months}\n")
    file.write(f"Total: ${net}\n")
    file.write(f"Average change: ${average_change}\n")
    file.write(f"Greatest increase in profits: {date1} (${greatest}) \n")
    file.write(f"Greatest decrease in profits: {date2} (${smallest})\n")

# Print the analysis to the console
with open(output_file, "r") as file:
    print(file.read())
